######################################################################
# Automatically generated by qmake (3.1) Mon Mar 13 18:25:30 2017
######################################################################

TEMPLATE = app
TARGET = xml_viewer
INCLUDEPATH += .

# Input
HEADERS += main_window.h utils.h xml_tree.h xml_node_display.h
SOURCES += main.cpp main_window.cpp xml_tree.cpp xml_node_display.cpp
QT += widgets xml
